### ISSUE TITLE
gfortran warning solved on M1 macOS 11.6.2

### ISSUE THREAD

**Issue by wyq977** [RubD/Giotto_site#11]
Hi, I found out that the even with R 4.2.0 and apple silicon Macs, gfortran can still be installed manally following the instruction [here](https://mac.r-project.org/tools/). Updates on https://rubd.github.io/Giotto_site/articles/installation_issues.html#errors-on-macos might be needed. I can make a pull requests if needed on gfortran on you can simply refer users [here](https://mac.r-project.org/tools/)

This is specific to Apple silicon Macs, an experimental build of GNU Fortran compiler is required otherwise errors like these would pop up during installation:

```error
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
```

This is due to [no Fortran compiler](https://support.bioconductor.org/p/9138121/) and it can be solved with an experimental build given that the R is installed at `/opt/R/arm64/` via Homebrew 

```bash
# for R>=4.2.0
curl -O https://mac.r-project.org/tools/gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz

# unpack
sudo tar fxz gfortran-12.0.1-20220312-is-darwin20-arm64.tar.xz -C /

# /opt/R/arm64/gfortran/SDK has to point to your macOS SDK
sudo gfortran-update-sdk
```

Ref: https://support.bioconductor.org/p/9138121/

**Comment by wyq977** [comment]
@RubD Hi?

**Comment by drieslab** [comment]
Thanks for the suggestion @wyq977 . If you want you can update the installation_issues file with your suggestion.

**Comment by wyq977** [comment]
@drieslab Hi, I added the guide on m1 and new apple silicon macs, on `rmd` only. I didn't build the html, you can review and build it.

Thx

**Comment by drieslab** [comment]
Perfect, thanks!

**Comment by mikeroswell** [comment]
I wasn't clear how to update the sdk: 

```
sudo gfortran-update-sdk
sudo: gfortran-update-sdk: command not found
````

**Comment by RubD** [comment]
Could you post this on the Giotto issues channel? https://github.com/drieslab/Giotto/issues 

This repo is for the old website and will be deleted in the future.

**Comment by anniliu9** [comment]
I was confused about updating the sdk:

sudo gfortran-update-sdk
sudo: gfortran-update-sdk: command not found
